-- ============================================================
-- BẢNG TỪ VỰNG HSK1 + HSK2
-- Chạy trong Supabase SQL Editor
-- ============================================================

CREATE TABLE IF NOT EXISTS vocabulary (
  id                SERIAL PRIMARY KEY,
  chinese_char      TEXT NOT NULL,
  pinyin            TEXT NOT NULL,
  pinyin_no_tone    TEXT NOT NULL,
  vietnamese_meaning TEXT,
  level             TEXT NOT NULL CHECK (level IN ('HSK1','HSK2'))
);

-- Index để tra cứu nhanh
CREATE INDEX IF NOT EXISTS idx_vocab_level        ON vocabulary (level);
CREATE INDEX IF NOT EXISTS idx_vocab_pinyin       ON vocabulary (pinyin_no_tone);
CREATE INDEX IF NOT EXISTS idx_vocab_pinyin_tone  ON vocabulary (pinyin);

-- Xóa dữ liệu cũ nếu chạy lại
TRUNCATE TABLE vocabulary RESTART IDENTITY;

-- ============================================================
-- HSK1 (150 từ)
-- ============================================================
INSERT INTO vocabulary (chinese_char, pinyin, pinyin_no_tone, vietnamese_meaning, level) VALUES
('爱',    'ài',           'ai',           'yêu thương',                 'HSK1'),
('八',    'bā',           'ba',           'tám',                        'HSK1'),
('爸爸',  'bàba',         'baba',         'bố, cha',                    'HSK1'),
('杯子',  'bēizi',        'beizi',        'cái cốc, ly',                'HSK1'),
('北京',  'Běijīng',      'Beijing',      'Bắc Kinh',                   'HSK1'),
('本',    'běn',          'ben',          'cuốn (lượng từ cho sách)',    'HSK1'),
('不',    'bù',           'bu',           'không',                      'HSK1'),
('不客气','bú kèqi',      'bu keqi',      'không có gì',                'HSK1'),
('菜',    'cài',          'cai',          'rau, thức ăn',               'HSK1'),
('茶',    'chá',          'cha',          'trà',                        'HSK1'),
('吃',    'chī',          'chi',          'ăn',                         'HSK1'),
('出租车','chūzūchē',     'chuzuche',     'xe taxi',                    'HSK1'),
('打电话','dǎ diànhuà',   'da dianhua',   'gọi điện thoại',             'HSK1'),
('大',    'dà',           'da',           'lớn, to',                    'HSK1'),
('的',    'de',           'de',           'của (trợ từ)',                'HSK1'),
('点',    'diǎn',         'dian',         'giờ, điểm',                  'HSK1'),
('电脑',  'diànnǎo',      'diannao',      'máy tính',                   'HSK1'),
('电视',  'diànshì',      'dianshi',      'tivi',                       'HSK1'),
('电影',  'diànyǐng',     'dianying',     'phim điện ảnh',              'HSK1'),
('东西',  'dōngxi',       'dongxi',       'đồ vật, thứ',                'HSK1'),
('都',    'dōu',          'dou',          'đều, cũng',                  'HSK1'),
('读',    'dú',           'du',           'đọc',                        'HSK1'),
('对不起','duìbuqǐ',      'duibuqi',      'xin lỗi',                    'HSK1'),
('多',    'duō',          'duo',          'nhiều',                      'HSK1'),
('多少',  'duōshao',      'duoshao',      'bao nhiêu',                  'HSK1'),
('儿子',  'érzi',         'erzi',         'con trai',                   'HSK1'),
('二',    'èr',           'er',           'hai',                        'HSK1'),
('饭馆',  'fànguǎn',      'fanguan',      'nhà hàng',                   'HSK1'),
('飞机',  'fēijī',        'feiji',        'máy bay',                    'HSK1'),
('分钟',  'fēnzhōng',     'fenzhong',     'phút',                       'HSK1'),
('高兴',  'gāoxìng',      'gaoxing',      'vui mừng',                   'HSK1'),
('个',    'gè',           'ge',           'cái (lượng từ chung)',        'HSK1'),
('工作',  'gōngzuò',      'gongzuo',      'công việc, làm việc',        'HSK1'),
('狗',    'gǒu',          'gou',          'chó',                        'HSK1'),
('汉语',  'Hànyǔ',        'Hanyu',        'tiếng Trung',                'HSK1'),
('好',    'hǎo',          'hao',          'tốt, khỏe',                  'HSK1'),
('好吃',  'hǎochī',       'haochi',       'ngon',                       'HSK1'),
('号',    'hào',          'hao',          'số, ngày tháng',             'HSK1'),
('喝',    'hē',           'he',           'uống',                       'HSK1'),
('和',    'hé',           'he',           'và',                         'HSK1'),
('很',    'hěn',          'hen',          'rất',                        'HSK1'),
('后面',  'hòumiàn',      'houmian',      'phía sau',                   'HSK1'),
('回',    'huí',          'hui',          'quay về, trở về',            'HSK1'),
('会',    'huì',          'hui',          'biết, có thể',               'HSK1'),
('几',    'jǐ',           'ji',           'mấy, vài',                   'HSK1'),
('家',    'jiā',          'jia',          'nhà, gia đình',              'HSK1'),
('叫',    'jiào',         'jiao',         'tên là, gọi là',             'HSK1'),
('今天',  'jīntiān',      'jintian',      'hôm nay',                    'HSK1'),
('九',    'jiǔ',          'jiu',          'chín',                       'HSK1'),
('开',    'kāi',          'kai',          'mở',                         'HSK1'),
('看',    'kàn',          'kan',          'xem, nhìn',                  'HSK1'),
('看见',  'kànjiàn',      'kanjian',      'nhìn thấy',                  'HSK1'),
('块',    'kuài',         'kuai',         'đồng (tiền), miếng',         'HSK1'),
('来',    'lái',          'lai',          'đến',                        'HSK1'),
('老师',  'lǎoshī',       'laoshi',       'giáo viên',                  'HSK1'),
('了',    'le',           'le',           'rồi (trợ từ hoàn thành)',    'HSK1'),
('里',    'lǐ',           'li',           'trong, bên trong',           'HSK1'),
('六',    'liù',          'liu',          'sáu',                        'HSK1'),
('妈妈',  'māma',         'mama',         'mẹ',                         'HSK1'),
('吗',    'ma',           'ma',           'à (trợ từ nghi vấn)',        'HSK1'),
('买',    'mǎi',          'mai',          'mua',                        'HSK1'),
('猫',    'māo',          'mao',          'mèo',                        'HSK1'),
('没',    'méi',          'mei',          'không có, chưa',             'HSK1'),
('没关系','méi guānxi',   'mei guanxi',   'không sao',                  'HSK1'),
('米饭',  'mǐfàn',        'mifan',        'cơm',                        'HSK1'),
('明天',  'míngtiān',     'mingtian',     'ngày mai',                   'HSK1'),
('名字',  'míngzi',       'mingzi',       'tên',                        'HSK1'),
('哪',    'nǎ',           'na',           'cái nào',                    'HSK1'),
('哪儿',  'nǎr',          'nar',          'ở đâu',                      'HSK1'),
('那',    'nà',           'na',           'cái đó, kia',                'HSK1'),
('呢',    'ne',           'ne',           'thì...à (trợ từ)',            'HSK1'),
('能',    'néng',         'neng',         'có thể',                     'HSK1'),
('你',    'nǐ',           'ni',           'bạn (ngôi 2 số ít)',         'HSK1'),
('你好',  'nǐ hǎo',       'ni hao',       'xin chào',                   'HSK1'),
('年',    'nián',         'nian',         'năm',                        'HSK1'),
('女儿',  'nǚér',         'nüer',         'con gái',                    'HSK1'),
('女人',  'nǚrén',        'nüren',        'người phụ nữ',               'HSK1'),
('朋友',  'péngyou',      'pengyou',      'bạn bè',                     'HSK1'),
('漂亮',  'piàoliang',    'piaoliang',    'đẹp',                        'HSK1'),
('苹果',  'píngguǒ',      'pingguo',      'táo',                        'HSK1'),
('七',    'qī',           'qi',           'bảy',                        'HSK1'),
('钱',    'qián',         'qian',         'tiền',                       'HSK1'),
('前面',  'qiánmiàn',     'qianmian',     'phía trước',                 'HSK1'),
('请',    'qǐng',         'qing',         'mời, xin',                   'HSK1'),
('去',    'qù',           'qu',           'đi',                         'HSK1'),
('热',    'rè',           're',           'nóng',                       'HSK1'),
('人',    'rén',          'ren',          'người',                      'HSK1'),
('认识',  'rènshi',       'renshi',       'quen biết',                  'HSK1'),
('日',    'rì',           'ri',           'ngày',                       'HSK1'),
('三',    'sān',          'san',          'ba',                         'HSK1'),
('商店',  'shāngdiàn',    'shangdian',    'cửa hàng',                   'HSK1'),
('上',    'shàng',        'shang',        'trên',                       'HSK1'),
('上午',  'shàngwǔ',      'shangwu',      'buổi sáng',                  'HSK1'),
('少',    'shǎo',         'shao',         'ít',                         'HSK1'),
('谁',    'shéi',         'shei',         'ai',                         'HSK1'),
('什么',  'shénme',       'shenme',       'cái gì',                     'HSK1'),
('十',    'shí',          'shi',          'mười',                       'HSK1'),
('时候',  'shíhou',       'shihou',       'lúc, thời điểm',             'HSK1'),
('是',    'shì',          'shi',          'là',                         'HSK1'),
('书',    'shū',          'shu',          'sách',                       'HSK1'),
('水',    'shuǐ',         'shui',         'nước',                       'HSK1'),
('水果',  'shuǐguǒ',      'shuiguo',      'hoa quả',                    'HSK1'),
('睡觉',  'shuìjiào',     'shuijiao',     'ngủ',                        'HSK1'),
('说',    'shuō',         'shuo',         'nói',                        'HSK1'),
('四',    'sì',           'si',           'bốn',                        'HSK1'),
('岁',    'suì',          'sui',          'tuổi',                       'HSK1'),
('他',    'tā',           'ta',           'anh ấy, ông ấy',             'HSK1'),
('她',    'tā',           'ta',           'cô ấy, bà ấy',               'HSK1'),
('太',    'tài',          'tai',          'quá',                        'HSK1'),
('天气',  'tiānqì',       'tianqi',       'thời tiết',                  'HSK1'),
('听',    'tīng',         'ting',         'nghe',                       'HSK1'),
('同学',  'tóngxué',      'tongxue',      'bạn cùng lớp',               'HSK1'),
('喂',    'wèi',          'wei',          'alo (trả lời điện thoại)',    'HSK1'),
('我',    'wǒ',           'wo',           'tôi',                        'HSK1'),
('我们',  'wǒmen',        'women',        'chúng tôi',                  'HSK1'),
('五',    'wǔ',           'wu',           'năm (số)',                   'HSK1'),
('喜欢',  'xǐhuan',       'xihuan',       'thích',                      'HSK1'),
('下',    'xià',          'xia',          'dưới',                       'HSK1'),
('下午',  'xiàwǔ',        'xiawu',        'buổi chiều',                 'HSK1'),
('下雨',  'xià yǔ',       'xia yu',       'mưa',                        'HSK1'),
('先生',  'xiānsheng',    'xiansheng',    'ông, thầy',                  'HSK1'),
('现在',  'xiànzài',      'xianzai',      'bây giờ',                    'HSK1'),
('想',    'xiǎng',        'xiang',        'muốn, nghĩ',                 'HSK1'),
('小',    'xiǎo',         'xiao',         'nhỏ, bé',                    'HSK1'),
('小姐',  'xiǎojiě',      'xiaojie',      'cô (cách gọi)',               'HSK1'),
('些',    'xiē',          'xie',          'một vài',                    'HSK1'),
('写',    'xiě',          'xie',          'viết',                       'HSK1'),
('谢谢',  'xièxie',       'xiexie',       'cảm ơn',                     'HSK1'),
('星期',  'xīngqī',       'xingqi',       'tuần, thứ',                  'HSK1'),
('学生',  'xuésheng',     'xuesheng',     'học sinh',                   'HSK1'),
('学习',  'xuéxí',        'xuexi',        'học tập',                    'HSK1'),
('学校',  'xuéxiào',      'xuexiao',      'trường học',                 'HSK1'),
('一',    'yī',           'yi',           'một',                        'HSK1'),
('一点儿','yīdiǎnr',      'yidianr',      'một chút',                   'HSK1'),
('衣服',  'yīfu',         'yifu',         'quần áo',                    'HSK1'),
('医生',  'yīshēng',      'yisheng',      'bác sĩ',                     'HSK1'),
('医院',  'yīyuàn',       'yiyuan',       'bệnh viện',                  'HSK1'),
('椅子',  'yǐzi',         'yizi',         'ghế',                        'HSK1'),
('有',    'yǒu',          'you',          'có',                         'HSK1'),
('月',    'yuè',          'yue',          'tháng',                      'HSK1'),
('再见',  'zàijiàn',      'zaijian',      'tạm biệt',                   'HSK1'),
('在',    'zài',          'zai',          'ở, đang',                    'HSK1'),
('怎么',  'zěnme',        'zenme',        'thế nào, làm thế nào',       'HSK1'),
('怎么样','zěnmeyàng',    'zenmeyang',    'thế nào rồi',                'HSK1'),
('这',    'zhè',          'zhe',          'cái này',                    'HSK1'),
('中国',  'Zhōngguó',     'Zhongguo',     'Trung Quốc',                 'HSK1'),
('中午',  'zhōngwǔ',      'zhongwu',      'buổi trưa',                  'HSK1'),
('住',    'zhù',          'zhu',          'ở, sống',                    'HSK1'),
('桌子',  'zhuōzi',       'zhuozi',       'bàn',                        'HSK1'),
('字',    'zì',           'zi',           'chữ, ký tự',                 'HSK1'),
('坐',    'zuò',          'zuo',          'ngồi, đi (phương tiện)',      'HSK1'),
('做',    'zuò',          'zuo',          'làm',                        'HSK1');

-- ============================================================
-- HSK2 (150 từ)
-- ============================================================
INSERT INTO vocabulary (chinese_char, pinyin, pinyin_no_tone, vietnamese_meaning, level) VALUES
('吧',    'ba',           'ba',           'thôi, nhé (trợ từ)',         'HSK2'),
('白',    'bái',          'bai',          'trắng',                      'HSK2'),
('百',    'bǎi',          'bai',          'trăm',                       'HSK2'),
('帮助',  'bāngzhù',      'bangzhu',      'giúp đỡ',                    'HSK2'),
('报纸',  'bàozhǐ',       'baozhi',       'tờ báo',                     'HSK2'),
('比',    'bǐ',           'bi',           'so với',                     'HSK2'),
('别',    'bié',          'bie',          'đừng',                       'HSK2'),
('宾馆',  'bīnguǎn',      'binguan',      'khách sạn',                  'HSK2'),
('长',    'cháng',        'chang',        'dài',                        'HSK2'),
('唱歌',  'chàng gē',     'chang ge',     'hát',                        'HSK2'),
('出',    'chū',          'chu',          'ra, xuất',                   'HSK2'),
('穿',    'chuān',        'chuan',        'mặc (quần áo)',               'HSK2'),
('次',    'cì',           'ci',           'lần',                        'HSK2'),
('从',    'cóng',         'cong',         'từ',                         'HSK2'),
('错',    'cuò',          'cuo',          'sai',                        'HSK2'),
('打篮球','dǎ lánqiú',    'da lanqiu',    'chơi bóng rổ',               'HSK2'),
('大家',  'dàjiā',        'dajia',        'mọi người',                  'HSK2'),
('到',    'dào',          'dao',          'đến, đạt',                   'HSK2'),
('得',    'de',           'de',           'được (trợ từ kết quả)',       'HSK2'),
('等',    'děng',         'deng',         'chờ, đợi',                   'HSK2'),
('弟弟',  'dìdi',         'didi',         'em trai',                    'HSK2'),
('第一',  'dì yī',        'di yi',        'thứ nhất',                   'HSK2'),
('地图',  'dìtú',         'ditu',         'bản đồ',                     'HSK2'),
('地铁',  'dìtiě',        'ditie',        'tàu điện ngầm',              'HSK2'),
('动物',  'dòngwù',       'dongwu',       'động vật',                   'HSK2'),
('对',    'duì',          'dui',          'đúng',                       'HSK2'),
('房间',  'fángjiān',     'fangjian',     'phòng',                      'HSK2'),
('非常',  'fēicháng',     'feichang',     'rất, cực kỳ',                'HSK2'),
('服务员','fúwùyuán',     'fuwuyuan',     'nhân viên phục vụ',          'HSK2'),
('告诉',  'gàosù',        'gaosu',        'nói cho biết',               'HSK2'),
('哥哥',  'gēge',         'gege',         'anh trai',                   'HSK2'),
('给',    'gěi',          'gei',          'cho, đưa',                   'HSK2'),
('公共汽车','gōnggòng qìchē','gonggong qiche','xe buýt',                'HSK2'),
('公司',  'gōngsī',       'gongsi',       'công ty',                    'HSK2'),
('贵',    'guì',          'gui',          'đắt tiền',                   'HSK2'),
('过',    'guò',          'guo',          'qua, đã từng',               'HSK2'),
('还',    'hái',          'hai',          'còn, vẫn',                   'HSK2'),
('害怕',  'hàipà',        'haipa',        'sợ hãi',                     'HSK2'),
('黑板',  'hēibǎn',       'heiban',       'bảng đen',                   'HSK2'),
('红',    'hóng',         'hong',         'đỏ',                         'HSK2'),
('火车站','huǒchēzhàn',   'huochezhán',   'ga tàu hỏa',                 'HSK2'),
('机场',  'jīchǎng',      'jichang',      'sân bay',                    'HSK2'),
('鸡蛋',  'jīdàn',        'jidan',        'trứng gà',                   'HSK2'),
('件',    'jiàn',         'jian',         'cái (lượng từ cho áo)',       'HSK2'),
('教室',  'jiàoshì',      'jiaoshi',      'phòng học, lớp học',         'HSK2'),
('姐姐',  'jiějie',       'jiejie',       'chị gái',                    'HSK2'),
('介绍',  'jièshào',      'jieshao',      'giới thiệu',                 'HSK2'),
('进',    'jìn',          'jin',          'vào, đi vào',                'HSK2'),
('近',    'jìn',          'jin',          'gần',                        'HSK2'),
('觉得',  'juéde',        'juede',        'cảm thấy',                   'HSK2'),
('咖啡',  'kāfēi',        'kafei',        'cà phê',                     'HSK2'),
('开始',  'kāishǐ',       'kaishi',       'bắt đầu',                    'HSK2'),
('考试',  'kǎoshì',       'kaoshi',       'thi, kỳ thi',                'HSK2'),
('可能',  'kěnéng',       'keneng',       'có thể, có lẽ',              'HSK2'),
('可以',  'kěyǐ',         'keyi',         'có thể, được phép',          'HSK2'),
('课',    'kè',           'ke',           'bài học, tiết học',          'HSK2'),
('快',    'kuài',         'kuai',         'nhanh',                      'HSK2'),
('快乐',  'kuàilè',       'kuaile',       'vui vẻ, hạnh phúc',          'HSK2'),
('累',    'lèi',          'lei',          'mệt mỏi',                    'HSK2'),
('离',    'lí',           'li',           'cách (khoảng cách)',          'HSK2'),
('脸',    'liǎn',         'lian',         'mặt (khuôn mặt)',             'HSK2'),
('两',    'liǎng',        'liang',        'hai',                        'HSK2'),
('零',    'líng',         'ling',         'không (số 0)',                'HSK2'),
('路',    'lù',           'lu',           'đường, con đường',           'HSK2'),
('旅游',  'lǚyóu',        'lüyou',        'du lịch',                    'HSK2'),
('卖',    'mài',          'mai',          'bán',                        'HSK2'),
('慢',    'màn',          'man',          'chậm',                       'HSK2'),
('忙',    'máng',         'mang',         'bận rộn',                    'HSK2'),
('每',    'měi',          'mei',          'mỗi',                        'HSK2'),
('妹妹',  'mèimei',       'meimei',       'em gái',                     'HSK2'),
('门',    'mén',          'men',          'cửa',                        'HSK2'),
('面条',  'miàntiáo',     'miantiao',     'mì sợi',                     'HSK2'),
('男人',  'nánrén',       'nanren',       'người đàn ông',              'HSK2'),
('您',    'nín',          'nin',          'bạn (kính ngữ)',              'HSK2'),
('牛奶',  'niúnǎi',       'niunai',       'sữa bò',                     'HSK2'),
('努力',  'nǔlì',         'nuli',         'cố gắng, chăm chỉ',          'HSK2'),
('爬山',  'pá shān',      'pa shan',      'leo núi',                    'HSK2'),
('跑步',  'pǎo bù',       'pao bu',       'chạy bộ',                    'HSK2'),
('便宜',  'piányí',       'pianyi',       'rẻ, giá rẻ',                 'HSK2'),
('票',    'piào',         'piao',         'vé',                         'HSK2'),
('妻子',  'qīzi',         'qizi',         'vợ',                         'HSK2'),
('起床',  'qǐ chuáng',    'qi chuang',    'thức dậy',                   'HSK2'),
('千',    'qiān',         'qian',         'nghìn',                      'HSK2'),
('铅笔',  'qiānbǐ',       'qianbi',       'bút chì',                    'HSK2'),
('清楚',  'qīngchǔ',      'qingchu',      'rõ ràng',                    'HSK2'),
('去年',  'qùnián',       'qunian',       'năm ngoái',                  'HSK2'),
('让',    'ràng',         'rang',         'để, cho phép',               'HSK2'),
('认为',  'rènwéi',       'renwei',       'cho rằng, nghĩ rằng',        'HSK2'),
('如果',  'rúguǒ',        'ruguo',        'nếu',                        'HSK2'),
('上班',  'shàng bān',    'shang ban',    'đi làm',                     'HSK2'),
('身体',  'shēntǐ',       'shenti',       'cơ thể, sức khỏe',           'HSK2'),
('生病',  'shēng bìng',   'sheng bing',   'bị ốm',                      'HSK2'),
('生日',  'shēngrì',      'shengri',      'sinh nhật',                  'HSK2'),
('时间',  'shíjiān',      'shijian',      'thời gian',                  'HSK2'),
('事情',  'shìqíng',      'shiqing',      'sự việc, chuyện',            'HSK2'),
('手机',  'shǒujī',       'shouji',       'điện thoại di động',         'HSK2'),
('手表',  'shǒubiǎo',     'shoubiao',     'đồng hồ đeo tay',            'HSK2'),
('树',    'shù',          'shu',          'cây',                        'HSK2'),
('说话',  'shuōhuà',      'shuohua',      'nói chuyện',                 'HSK2'),
('送',    'sòng',         'song',         'tặng, đưa đến',              'HSK2'),
('虽然',  'suīrán',       'suiran',       'mặc dù',                     'HSK2'),
('它',    'tā',           'ta',           'nó (con vật / đồ vật)',       'HSK2'),
('踢足球','tī zúqiú',     'ti zuqiu',     'đá bóng',                    'HSK2'),
('题',    'tí',           'ti',           'bài, câu hỏi',               'HSK2'),
('跳舞',  'tiào wǔ',      'tiao wu',      'nhảy múa',                   'HSK2'),
('外',    'wài',          'wai',          'ngoài, bên ngoài',           'HSK2'),
('完',    'wán',          'wan',          'xong, hết',                  'HSK2'),
('玩',    'wán',          'wan',          'chơi',                       'HSK2'),
('晚上',  'wǎnshang',     'wanshang',     'buổi tối',                   'HSK2'),
('往',    'wǎng',         'wang',         'về phía, hướng',             'HSK2'),
('为什么','wèishénme',    'weishenme',    'tại sao',                    'HSK2'),
('问',    'wèn',          'wen',          'hỏi',                        'HSK2'),
('问题',  'wèntí',        'wenti',        'câu hỏi, vấn đề',            'HSK2'),
('西瓜',  'xīguā',        'xigua',        'dưa hấu',                    'HSK2'),
('希望',  'xīwàng',       'xiwang',       'hy vọng, mong muốn',         'HSK2'),
('洗',    'xǐ',           'xi',           'rửa, giặt',                  'HSK2'),
('洗手间','xǐshǒujiān',   'xishoujian',   'nhà vệ sinh',                'HSK2'),
('笑',    'xiào',         'xiao',         'cười',                       'HSK2'),
('新',    'xīn',          'xin',          'mới',                        'HSK2'),
('新闻',  'xīnwén',       'xinwen',       'tin tức',                    'HSK2'),
('姓',    'xìng',         'xing',         'họ (tên họ)',                 'HSK2'),
('休息',  'xiūxi',        'xiuxi',        'nghỉ ngơi',                  'HSK2'),
('需要',  'xūyào',        'xuyao',        'cần, cần thiết',             'HSK2'),
('雪',    'xuě',          'xue',          'tuyết',                      'HSK2'),
('颜色',  'yánsè',        'yanse',        'màu sắc',                    'HSK2'),
('眼睛',  'yǎnjīng',      'yanjing',      'mắt',                        'HSK2'),
('一起',  'yīqǐ',         'yiqi',         'cùng nhau',                  'HSK2'),
('一下',  'yīxià',        'yixia',        'một chút, thử',              'HSK2'),
('因为',  'yīnwèi',       'yinwei',       'vì, bởi vì',                 'HSK2'),
('音乐',  'yīnyuè',       'yinyue',       'âm nhạc',                    'HSK2'),
('游泳',  'yóuyǒng',      'youyong',      'bơi lội',                    'HSK2'),
('右边',  'yòubiān',      'youbian',      'bên phải',                   'HSK2'),
('鱼',    'yú',           'yu',           'cá',                         'HSK2'),
('远',    'yuǎn',         'yuan',         'xa',                         'HSK2'),
('运动',  'yùndòng',      'yundong',      'thể thao, vận động',         'HSK2'),
('再',    'zài',          'zai',          'nữa, lại',                   'HSK2'),
('早上',  'zǎoshang',     'zaoshang',     'buổi sáng sớm',              'HSK2'),
('昨天',  'zuótiān',      'zuotian',      'hôm qua',                    'HSK2'),
('丈夫',  'zhàngfu',      'zhangfu',      'chồng',                      'HSK2'),
('找',    'zhǎo',         'zhao',         'tìm',                        'HSK2'),
('着',    'zhe',          'zhe',          'đang (trợ từ trạng thái)',    'HSK2'),
('真',    'zhēn',         'zhen',         'thật, thực sự',              'HSK2'),
('正在',  'zhèngzài',     'zhengzai',     'đang (thực hiện)',            'HSK2'),
('知道',  'zhīdào',       'zhidao',       'biết',                       'HSK2'),
('只',    'zhǐ',          'zhi',          'chỉ',                        'HSK2'),
('中间',  'zhōngjiān',    'zhongjian',    'ở giữa',                     'HSK2'),
('准备',  'zhǔnbèi',      'zhunbei',      'chuẩn bị',                   'HSK2'),
('左边',  'zuǒbiān',      'zuobian',      'bên trái',                   'HSK2');
