-- ============================================================
-- HSK3 — Bổ sung từ vựng (chạy SAU file vocabulary_hsk.sql)
-- Chạy trong Supabase SQL Editor
-- ============================================================

-- 1) Nới ràng buộc CHECK để chấp nhận HSK3
ALTER TABLE vocabulary DROP CONSTRAINT IF EXISTS vocabulary_level_check;
ALTER TABLE vocabulary
  ADD CONSTRAINT vocabulary_level_check
  CHECK (level IN ('HSK1','HSK2','HSK3'));

-- 2) Xóa HSK3 cũ (để chạy lại nhiều lần không bị trùng)
DELETE FROM vocabulary WHERE level = 'HSK3';

-- 3) Nạp từ vựng HSK3 (300 từ mới)
INSERT INTO vocabulary (chinese_char, pinyin, pinyin_no_tone, vietnamese_meaning, level) VALUES
('阿姨',    'āyí',           'ayi',          'dì, cô (giúp việc)',            'HSK3'),
('啊',      'a',             'a',            'a (trợ từ)',                    'HSK3'),
('矮',      'ǎi',            'ai',           'thấp, lùn',                     'HSK3'),
('爱好',    'àihào',         'aihao',        'sở thích',                      'HSK3'),
('安静',    'ānjìng',        'anjing',       'yên tĩnh',                      'HSK3'),
('把',      'bǎ',            'ba',           'đem, lấy (giới từ)',            'HSK3'),
('班',      'bān',           'ban',          'lớp, ca',                       'HSK3'),
('搬',      'bān',           'ban',          'chuyển, dọn',                   'HSK3'),
('办法',    'bànfǎ',         'banfa',        'biện pháp, cách',               'HSK3'),
('办公室',  'bàngōngshì',    'bangongshi',   'văn phòng',                     'HSK3'),
('半',      'bàn',           'ban',          'một nửa',                       'HSK3'),
('帮忙',    'bāngmáng',      'bangmang',     'giúp đỡ',                       'HSK3'),
('包',      'bāo',           'bao',          'cái túi; gói',                  'HSK3'),
('饱',      'bǎo',           'bao',          'no',                            'HSK3'),
('北方',    'běifāng',       'beifang',      'phương bắc',                    'HSK3'),
('被',      'bèi',           'bei',          'bị, được (bị động)',            'HSK3'),
('鼻子',    'bízi',          'bizi',         'cái mũi',                       'HSK3'),
('比较',    'bǐjiào',        'bijiao',       'so sánh; tương đối',            'HSK3'),
('比赛',    'bǐsài',         'bisai',        'thi đấu, trận đấu',             'HSK3'),
('笔记本',  'bǐjìběn',       'bijiben',      'sổ tay, laptop',                'HSK3'),
('必须',    'bìxū',          'bixu',         'bắt buộc, phải',                'HSK3'),
('变化',    'biànhuà',       'bianhua',      'biến hóa, thay đổi',            'HSK3'),
('别人',    'biérén',        'bieren',       'người khác',                    'HSK3'),
('冰箱',    'bīngxiāng',     'bingxiang',    'tủ lạnh',                       'HSK3'),
('不但',    'búdàn',         'budan',        'không những',                   'HSK3'),
('菜单',    'càidān',        'caidan',       'thực đơn',                      'HSK3'),
('参加',    'cānjiā',        'canjia',       'tham gia',                      'HSK3'),
('草',      'cǎo',           'cao',          'cỏ',                            'HSK3'),
('层',      'céng',          'ceng',         'tầng, lớp',                     'HSK3'),
('差',      'chà',           'cha',          'kém, thiếu',                    'HSK3'),
('超市',    'chāoshì',       'chaoshi',      'siêu thị',                      'HSK3'),
('衬衫',    'chènshān',      'chenshan',     'áo sơ mi',                      'HSK3'),
('成绩',    'chéngjì',       'chengji',      'thành tích',                    'HSK3'),
('城市',    'chéngshì',      'chengshi',     'thành phố',                     'HSK3'),
('迟到',    'chídào',        'chidao',       'đến muộn',                      'HSK3'),
('出现',    'chūxiàn',       'chuxian',      'xuất hiện',                     'HSK3'),
('厨房',    'chúfáng',       'chufang',      'nhà bếp',                       'HSK3'),
('春',      'chūn',          'chun',         'mùa xuân',                      'HSK3'),
('词典',    'cídiǎn',        'cidian',       'từ điển',                       'HSK3'),
('聪明',    'cōngming',      'congming',     'thông minh',                    'HSK3'),
('打扫',    'dǎsǎo',         'dasao',        'quét dọn',                      'HSK3'),
('打算',    'dǎsuàn',        'dasuan',       'dự định, tính toán',            'HSK3'),
('带',      'dài',           'dai',          'mang, đem theo',                'HSK3'),
('担心',    'dānxīn',        'danxin',       'lo lắng',                       'HSK3'),
('蛋糕',    'dàngāo',        'dangao',       'bánh ga-tô',                    'HSK3'),
('当然',    'dāngrán',       'dangran',      'đương nhiên',                   'HSK3'),
('灯',      'dēng',          'deng',         'đèn',                           'HSK3'),
('地方',    'dìfang',        'difang',       'nơi, địa phương',               'HSK3'),
('地铁',    'dìtiě',         'ditie',        'tàu điện ngầm',                 'HSK3'),
('地图',    'dìtú',          'ditu',         'bản đồ',                        'HSK3'),
('电梯',    'diàntī',        'dianti',       'thang máy',                     'HSK3'),
('电子邮件','diànzǐyóujiàn', 'dianziyoujian','thư điện tử',                   'HSK3'),
('东',      'dōng',          'dong',         'phía đông',                     'HSK3'),
('冬',      'dōng',          'dong',         'mùa đông',                      'HSK3'),
('动物',    'dòngwù',        'dongwu',       'động vật',                      'HSK3'),
('短',      'duǎn',          'duan',         'ngắn',                          'HSK3'),
('段',      'duàn',          'duan',         'đoạn',                          'HSK3'),
('锻炼',    'duànliàn',      'duanlian',     'rèn luyện, tập luyện',          'HSK3'),
('多么',    'duōme',         'duome',        'biết bao, thật là',             'HSK3'),
('饿',      'è',             'e',            'đói',                           'HSK3'),
('耳朵',    'ěrduo',         'erduo',        'cái tai',                       'HSK3'),
('发',      'fā',            'fa',           'gửi, phát',                     'HSK3'),
('发烧',    'fāshāo',        'fashao',       'sốt',                           'HSK3'),
('发现',    'fāxiàn',        'faxian',       'phát hiện',                     'HSK3'),
('方便',    'fāngbiàn',      'fangbian',     'thuận tiện',                    'HSK3'),
('放',      'fàng',          'fang',         'đặt, để; thả',                  'HSK3'),
('放心',    'fàngxīn',       'fangxin',      'yên tâm',                       'HSK3'),
('分',      'fēn',           'fen',          'phút; chia; phân',              'HSK3'),
('附近',    'fùjìn',         'fujin',        'gần đây, lân cận',              'HSK3'),
('复习',    'fùxí',          'fuxi',         'ôn tập',                        'HSK3'),
('干净',    'gānjìng',       'ganjing',      'sạch sẽ',                       'HSK3'),
('感冒',    'gǎnmào',        'ganmao',       'cảm cúm',                       'HSK3'),
('感兴趣',  'gǎnxìngqù',     'ganxingqu',    'có hứng thú',                   'HSK3'),
('刚才',    'gāngcái',       'gangcai',      'vừa nãy',                       'HSK3'),
('个子',    'gèzi',          'gezi',         'vóc dáng, chiều cao',           'HSK3'),
('根据',    'gēnjù',         'genju',        'căn cứ, dựa vào',               'HSK3'),
('跟',      'gēn',           'gen',          'với, theo',                     'HSK3'),
('更',      'gèng',          'geng',         'càng, hơn',                     'HSK3'),
('公斤',    'gōngjīn',       'gongjin',      'ki-lô-gam',                     'HSK3'),
('公园',    'gōngyuán',      'gongyuan',     'công viên',                     'HSK3'),
('故事',    'gùshi',         'gushi',        'câu chuyện',                    'HSK3'),
('刮风',    'guāfēng',       'guafeng',      'nổi gió, có gió',               'HSK3'),
('关',      'guān',          'guan',         'đóng, tắt',                     'HSK3'),
('关系',    'guānxi',        'guanxi',       'quan hệ',                       'HSK3'),
('关心',    'guānxīn',       'guanxin',      'quan tâm',                      'HSK3'),
('关于',    'guānyú',        'guanyu',       'về, liên quan đến',             'HSK3'),
('国家',    'guójiā',        'guojia',       'quốc gia',                      'HSK3'),
('过',      'guò',           'guo',          'qua; đã từng',                  'HSK3'),
('过去',    'guòqù',         'guoqu',        'quá khứ; đi qua',               'HSK3'),
('还',      'hái',           'hai',          'còn, vẫn',                      'HSK3'),
('害怕',    'hàipà',         'haipa',        'sợ hãi',                        'HSK3'),
('黑板',    'hēibǎn',        'heiban',       'bảng đen',                      'HSK3'),
('护照',    'hùzhào',        'huzhao',       'hộ chiếu',                      'HSK3'),
('花',      'huā',           'hua',          'hoa; tiêu (tiền)',              'HSK3'),
('画',      'huà',           'hua',          'vẽ; bức tranh',                 'HSK3'),
('坏',      'huài',          'huai',         'xấu, hỏng',                     'HSK3'),
('环境',    'huánjìng',      'huanjing',     'môi trường',                    'HSK3'),
('还',      'huán',          'huan',         'trả lại',                       'HSK3'),
('换',      'huàn',          'huan',         'đổi, thay',                     'HSK3'),
('黄',      'huáng',         'huang',        'màu vàng',                      'HSK3'),
('回答',    'huídá',         'huida',        'trả lời',                       'HSK3'),
('会议',    'huìyì',         'huiyi',        'hội nghị, cuộc họp',            'HSK3'),
('火车站',  'huǒchēzhàn',    'huochezhan',   'ga tàu hỏa',                    'HSK3'),
('机会',    'jīhuì',         'jihui',        'cơ hội',                        'HSK3'),
('几乎',    'jīhū',          'jihu',         'hầu như',                       'HSK3'),
('极',      'jí',            'ji',           'cực kỳ',                        'HSK3'),
('记得',    'jìde',          'jide',         'nhớ',                           'HSK3'),
('季节',    'jìjié',         'jijie',        'mùa, mùa vụ',                   'HSK3'),
('检查',    'jiǎnchá',       'jiancha',      'kiểm tra',                      'HSK3'),
('简单',    'jiǎndān',       'jiandan',      'đơn giản',                      'HSK3'),
('见面',    'jiànmiàn',      'jianmian',     'gặp mặt',                       'HSK3'),
('健康',    'jiànkāng',      'jiankang',     'khỏe mạnh',                     'HSK3'),
('讲',      'jiǎng',         'jiang',        'giảng, nói',                    'HSK3'),
('教',      'jiāo',          'jiao',         'dạy',                           'HSK3'),
('角',      'jiǎo',          'jiao',         'góc; hào (tiền)',               'HSK3'),
('脚',      'jiǎo',          'jiao',         'bàn chân',                      'HSK3'),
('接',      'jiē',           'jie',          'đón; nối, nhận',                'HSK3'),
('街道',    'jiēdào',        'jiedao',       'đường phố',                     'HSK3'),
('节目',    'jiémù',         'jiemu',        'chương trình',                  'HSK3'),
('节日',    'jiérì',         'jieri',        'ngày lễ',                       'HSK3'),
('结婚',    'jiéhūn',        'jiehun',       'kết hôn',                       'HSK3'),
('结束',    'jiéshù',        'jieshu',       'kết thúc',                      'HSK3'),
('解决',    'jiějué',        'jiejue',       'giải quyết',                    'HSK3'),
('借',      'jiè',           'jie',          'mượn, cho mượn',                'HSK3'),
('经常',    'jīngcháng',     'jingchang',    'thường xuyên',                  'HSK3'),
('经过',    'jīngguò',       'jingguo',      'trải qua, đi qua',              'HSK3'),
('经理',    'jīnglǐ',        'jingli',       'giám đốc',                      'HSK3'),
('久',      'jiǔ',           'jiu',          'lâu',                           'HSK3'),
('旧',      'jiù',           'jiu',          'cũ',                            'HSK3'),
('举行',    'jǔxíng',        'juxing',       'tổ chức (sự kiện)',             'HSK3'),
('句子',    'jùzi',          'juzi',         'câu',                           'HSK3'),
('决定',    'juédìng',       'jueding',      'quyết định',                    'HSK3'),
('渴',      'kě',            'ke',           'khát',                          'HSK3'),
('可爱',    'kě''ài',        'keai',         'đáng yêu',                      'HSK3'),
('刻',      'kè',            'ke',           'khắc (15 phút)',                'HSK3'),
('客人',    'kèrén',         'keren',        'khách',                         'HSK3'),
('空调',    'kōngtiáo',      'kongtiao',     'điều hòa',                      'HSK3'),
('口',      'kǒu',           'kou',          'miệng; (lượng từ)',             'HSK3'),
('哭',      'kū',            'ku',           'khóc',                          'HSK3'),
('裤子',    'kùzi',          'kuzi',         'quần',                          'HSK3'),
('筷子',    'kuàizi',        'kuaizi',       'đũa',                           'HSK3'),
('蓝',      'lán',           'lan',          'màu xanh dương',                'HSK3'),
('老',      'lǎo',           'lao',          'già; cũ',                       'HSK3'),
('离开',    'líkāi',         'likai',        'rời khỏi',                      'HSK3'),
('礼物',    'lǐwù',          'liwu',         'quà tặng',                      'HSK3'),
('历史',    'lìshǐ',         'lishi',        'lịch sử',                       'HSK3'),
('脸',      'liǎn',          'lian',         'khuôn mặt',                     'HSK3'),
('练习',    'liànxí',        'lianxi',       'luyện tập',                     'HSK3'),
('两',      'liǎng',         'liang',        'hai (số lượng)',                'HSK3'),
('辆',      'liàng',         'liang',        'chiếc (xe)',                    'HSK3'),
('聊天',    'liáotiān',      'liaotian',     'trò chuyện',                    'HSK3'),
('了解',    'liǎojiě',       'liaojie',      'tìm hiểu, hiểu rõ',             'HSK3'),
('邻居',    'línjū',         'linju',        'hàng xóm',                      'HSK3'),
('留学',    'liúxué',        'liuxue',       'du học',                        'HSK3'),
('楼',      'lóu',           'lou',          'tầng lầu, tòa nhà',             'HSK3'),
('绿',      'lǜ',            'lu',           'màu xanh lá',                   'HSK3'),
('马',      'mǎ',            'ma',           'con ngựa',                      'HSK3'),
('马上',    'mǎshàng',       'mashang',      'lập tức, ngay',                 'HSK3'),
('满意',    'mǎnyì',         'manyi',        'hài lòng',                      'HSK3'),
('帽子',    'màozi',         'maozi',        'cái mũ',                        'HSK3'),
('米',      'mǐ',            'mi',           'gạo; mét',                      'HSK3'),
('面包',    'miànbāo',       'mianbao',      'bánh mì',                       'HSK3'),
('明白',    'míngbai',       'mingbai',      'hiểu rõ',                       'HSK3'),
('拿',      'ná',            'na',           'cầm, lấy',                      'HSK3'),
('奶奶',    'nǎinai',        'nainai',       'bà nội',                        'HSK3'),
('南',      'nán',           'nan',          'phía nam',                      'HSK3'),
('难',      'nán',           'nan',          'khó',                           'HSK3'),
('难过',    'nánguò',        'nanguo',       'buồn bã',                       'HSK3'),
('年级',    'niánjí',        'nianji',       'khối lớp',                      'HSK3'),
('年轻',    'niánqīng',      'nianqing',     'trẻ tuổi',                      'HSK3'),
('鸟',      'niǎo',          'niao',         'con chim',                      'HSK3'),
('努力',    'nǔlì',          'nuli',         'nỗ lực',                        'HSK3'),
('爬山',    'páshān',        'pashan',       'leo núi',                       'HSK3'),
('盘子',    'pánzi',         'panzi',        'cái đĩa',                       'HSK3'),
('胖',      'pàng',          'pang',         'béo, mập',                      'HSK3'),
('啤酒',    'píjiǔ',         'pijiu',        'bia',                           'HSK3'),
('葡萄',    'pútáo',         'putao',        'nho',                           'HSK3'),
('普通话',  'pǔtōnghuà',     'putonghua',    'tiếng phổ thông',               'HSK3'),
('其实',    'qíshí',         'qishi',        'thực ra',                       'HSK3'),
('其他',    'qítā',          'qita',         'khác, còn lại',                 'HSK3'),
('奇怪',    'qíguài',        'qiguai',       'kỳ lạ',                         'HSK3'),
('骑',      'qí',            'qi',           'cưỡi, đi (xe)',                 'HSK3'),
('起飞',    'qǐfēi',         'qifei',        'cất cánh',                      'HSK3'),
('起来',    'qǐlái',         'qilai',        'đứng dậy; lên',                 'HSK3'),
('清楚',    'qīngchu',       'qingchu',      'rõ ràng',                       'HSK3'),
('请假',    'qǐngjià',       'qingjia',      'xin nghỉ phép',                 'HSK3'),
('秋',      'qiū',           'qiu',          'mùa thu',                       'HSK3'),
('裙子',    'qúnzi',         'qunzi',        'váy',                           'HSK3'),
('然后',    'ránhòu',        'ranhou',       'sau đó',                        'HSK3'),
('热情',    'rèqíng',        'reqing',       'nhiệt tình',                    'HSK3'),
('认为',    'rènwéi',        'renwei',       'cho rằng',                      'HSK3'),
('认真',    'rènzhēn',       'renzhen',      'nghiêm túc',                    'HSK3'),
('容易',    'róngyì',        'rongyi',       'dễ dàng',                       'HSK3'),
('如果',    'rúguǒ',         'ruguo',        'nếu như',                       'HSK3'),
('伞',      'sǎn',           'san',          'cái ô, dù',                     'HSK3'),
('上网',    'shàngwǎng',     'shangwang',    'lên mạng',                      'HSK3'),
('生气',    'shēngqì',       'shengqi',      'tức giận',                      'HSK3'),
('声音',    'shēngyīn',      'shengyin',     'âm thanh, giọng',               'HSK3'),
('世界',    'shìjiè',        'shijie',       'thế giới',                      'HSK3'),
('试',      'shì',           'shi',          'thử',                           'HSK3'),
('瘦',      'shòu',          'shou',         'gầy',                           'HSK3'),
('叔叔',    'shūshu',        'shushu',       'chú',                           'HSK3'),
('舒服',    'shūfu',         'shufu',        'thoải mái',                     'HSK3'),
('数学',    'shùxué',        'shuxue',       'toán học',                      'HSK3'),
('刷牙',    'shuāyá',        'shuaya',       'đánh răng',                     'HSK3'),
('双',      'shuāng',        'shuang',       'đôi, cặp',                      'HSK3'),
('水平',    'shuǐpíng',      'shuiping',     'trình độ',                      'HSK3'),
('司机',    'sījī',          'siji',         'tài xế',                        'HSK3'),
('太阳',    'tàiyáng',       'taiyang',      'mặt trời',                      'HSK3'),
('特别',    'tèbié',         'tebie',        'đặc biệt',                      'HSK3'),
('疼',      'téng',          'teng',         'đau',                           'HSK3'),
('提高',    'tígāo',         'tigao',        'nâng cao',                      'HSK3'),
('体育',    'tǐyù',          'tiyu',         'thể dục thể thao',              'HSK3'),
('甜',      'tián',          'tian',         'ngọt',                          'HSK3'),
('条',      'tiáo',          'tiao',         '(lượng từ vật dài)',            'HSK3'),
('同事',    'tóngshì',       'tongshi',      'đồng nghiệp',                   'HSK3'),
('同意',    'tóngyì',        'tongyi',       'đồng ý',                        'HSK3'),
('头发',    'tóufa',         'toufa',        'tóc',                           'HSK3'),
('突然',    'tūrán',         'turan',        'đột nhiên',                     'HSK3'),
('图书馆',  'túshūguǎn',     'tushuguan',    'thư viện',                      'HSK3'),
('腿',      'tuǐ',           'tui',          'chân (đùi)',                    'HSK3'),
('完成',    'wánchéng',      'wancheng',     'hoàn thành',                    'HSK3'),
('碗',      'wǎn',           'wan',          'cái bát',                       'HSK3'),
('万',      'wàn',           'wan',          'vạn (mười nghìn)',              'HSK3'),
('忘记',    'wàngjì',        'wangji',       'quên',                          'HSK3'),
('为',      'wèi',           'wei',          'vì, cho',                       'HSK3'),
('为了',    'wèile',         'weile',        'để, vì',                        'HSK3'),
('位',      'wèi',           'wei',          'vị (lượng từ người)',           'HSK3'),
('文化',    'wénhuà',        'wenhua',       'văn hóa',                       'HSK3'),
('西',      'xī',            'xi',           'phía tây',                      'HSK3'),
('习惯',    'xíguàn',        'xiguan',       'thói quen',                     'HSK3'),
('洗手间',  'xǐshǒujiān',    'xishoujian',   'nhà vệ sinh',                   'HSK3'),
('洗澡',    'xǐzǎo',         'xizao',        'tắm',                           'HSK3'),
('夏',      'xià',           'xia',          'mùa hè',                        'HSK3'),
('先',      'xiān',          'xian',         'trước, đầu tiên',               'HSK3'),
('相信',    'xiāngxìn',      'xiangxin',     'tin tưởng',                     'HSK3'),
('香蕉',    'xiāngjiāo',     'xiangjiao',    'chuối',                         'HSK3'),
('向',      'xiàng',         'xiang',        'hướng về, phía',                'HSK3'),
('像',      'xiàng',         'xiang',        'giống như',                     'HSK3'),
('小心',    'xiǎoxīn',       'xiaoxin',      'cẩn thận',                      'HSK3'),
('校长',    'xiàozhǎng',     'xiaozhang',    'hiệu trưởng',                   'HSK3'),
('新闻',    'xīnwén',        'xinwen',       'tin tức',                       'HSK3'),
('新鲜',    'xīnxiān',       'xinxian',      'tươi, mới mẻ',                  'HSK3'),
('信用卡',  'xìnyòngkǎ',     'xinyongka',    'thẻ tín dụng',                  'HSK3'),
('行李箱',  'xínglixiāng',   'xinglixiang',  'va li',                         'HSK3'),
('熊猫',    'xióngmāo',      'xiongmao',     'gấu trúc',                      'HSK3'),
('需要',    'xūyào',         'xuyao',        'cần',                           'HSK3'),
('选择',    'xuǎnzé',        'xuanze',       'lựa chọn',                      'HSK3'),
('眼镜',    'yǎnjìng',       'yanjing',      'kính mắt',                      'HSK3'),
('阳光',    'yángguāng',     'yangguang',    'ánh nắng',                      'HSK3'),
('要求',    'yāoqiú',        'yaoqiu',       'yêu cầu',                       'HSK3'),
('爷爷',    'yéye',          'yeye',         'ông nội',                       'HSK3'),
('一般',    'yìbān',         'yiban',        'thông thường, bình thường',     'HSK3'),
('一边',    'yìbiān',        'yibian',       'một bên; vừa...vừa',            'HSK3'),
('一定',    'yídìng',        'yiding',       'nhất định',                     'HSK3'),
('一共',    'yígòng',        'yigong',       'tổng cộng',                     'HSK3'),
('一会儿',  'yíhuìr',        'yihuir',       'một lát',                       'HSK3'),
('一样',    'yíyàng',        'yiyang',       'giống nhau',                    'HSK3'),
('一直',    'yìzhí',         'yizhi',        'luôn, thẳng',                   'HSK3'),
('以前',    'yǐqián',        'yiqian',       'trước đây',                     'HSK3'),
('以为',    'yǐwéi',         'yiwei',        'cứ tưởng',                      'HSK3'),
('音乐',    'yīnyuè',        'yinyue',       'âm nhạc',                       'HSK3'),
('银行',    'yínháng',       'yinhang',      'ngân hàng',                     'HSK3'),
('饮料',    'yǐnliào',       'yinliao',      'đồ uống',                       'HSK3'),
('应该',    'yīnggāi',       'yinggai',      'nên',                           'HSK3'),
('影响',    'yǐngxiǎng',     'yingxiang',    'ảnh hưởng',                     'HSK3'),
('用',      'yòng',          'yong',         'dùng',                          'HSK3'),
('游戏',    'yóuxì',         'youxi',        'trò chơi',                      'HSK3'),
('有名',    'yǒumíng',       'youming',      'nổi tiếng',                     'HSK3'),
('又',      'yòu',           'you',          'lại, vừa',                      'HSK3'),
('遇到',    'yùdào',         'yudao',        'gặp phải',                      'HSK3'),
('元',      'yuán',          'yuan',         'đồng (tiền)',                   'HSK3'),
('愿意',    'yuànyì',        'yuanyi',       'sẵn lòng',                      'HSK3'),
('月亮',    'yuèliang',      'yueliang',     'mặt trăng',                     'HSK3'),
('越',      'yuè',           'yue',          'càng',                          'HSK3'),
('云',      'yún',           'yun',          'mây',                           'HSK3'),
('站',      'zhàn',          'zhan',         'đứng; ga, trạm',                'HSK3'),
('张',      'zhāng',         'zhang',        '(lượng từ tờ, tấm)',            'HSK3'),
('长',      'zhǎng',         'zhang',        'mọc, lớn lên',                  'HSK3'),
('着急',    'zháojí',        'zhaoji',       'sốt ruột, lo lắng',             'HSK3'),
('照顾',    'zhàogu',        'zhaogu',       'chăm sóc',                      'HSK3'),
('照片',    'zhàopiàn',      'zhaopian',     'tấm ảnh',                       'HSK3'),
('照相机',  'zhàoxiàngjī',   'zhaoxiangji',  'máy ảnh',                       'HSK3'),
('只',      'zhī',           'zhi',          '(lượng từ con vật)',            'HSK3'),
('只有',    'zhǐyǒu',        'zhiyou',       'chỉ có',                        'HSK3'),
('中文',    'zhōngwén',      'zhongwen',     'tiếng Trung',                   'HSK3'),
('终于',    'zhōngyú',       'zhongyu',      'cuối cùng',                     'HSK3'),
('种',      'zhǒng',         'zhong',        'loại; (lượng từ)',              'HSK3'),
('重要',    'zhòngyào',      'zhongyao',     'quan trọng',                    'HSK3'),
('周末',    'zhōumò',        'zhoumo',       'cuối tuần',                     'HSK3'),
('主要',    'zhǔyào',        'zhuyao',       'chủ yếu',                       'HSK3'),
('注意',    'zhùyì',         'zhuyi',        'chú ý',                         'HSK3'),
('自己',    'zìjǐ',          'ziji',         'bản thân, tự mình',             'HSK3'),
('自行车',  'zìxíngchē',     'zixingche',    'xe đạp',                        'HSK3'),
('总是',    'zǒngshì',       'zongshi',      'luôn luôn',                     'HSK3'),
('嘴',      'zuǐ',           'zui',          'cái miệng',                     'HSK3'),
('最后',    'zuìhòu',        'zuihou',       'cuối cùng',                     'HSK3'),
('最近',    'zuìjìn',        'zuijin',       'gần đây',                       'HSK3'),
('作业',    'zuòyè',         'zuoye',        'bài tập về nhà',                'HSK3'),
('作用',    'zuòyòng',       'zuoyong',      'tác dụng',                      'HSK3');
