// Map pinyin (âm tiết + thanh điệu) → chữ Hán đại diện.
// Azure Speech zh-CN chỉ chấm Pronunciation Assessment chính xác khi
// ReferenceText là chữ Hán, KHÔNG phải pinyin Latinh.
// Khoá: pinyin không dấu + số thanh (1-4). Ví dụ "ba1" → "八".
// Hiển thị cho học viên vẫn là pinyin; chữ Hán chỉ dùng nội bộ gửi Azure.

export const PINYIN_TO_HANZI: Record<string, string> = {
  // b
  ba1:"八", ba2:"拔", ba3:"把", ba4:"爸",
  bo1:"波", bo2:"伯", bo3:"跛", bo4:"簸",
  bai1:"掰", bai2:"白", bai3:"百", bai4:"败",
  bei1:"杯", bei3:"北", bei4:"贝",
  bao1:"包", bao2:"薄", bao3:"宝", bao4:"报",
  ban1:"班", ban3:"板", ban4:"半",
  ben1:"奔", ben3:"本", ben4:"笨",
  bang1:"帮", bang3:"绑", bang4:"棒",
  beng1:"崩", beng2:"甭", beng3:"泵", beng4:"蹦",
  bi1:"逼", bi2:"鼻", bi3:"比", bi4:"必",
  bie1:"憋", bie2:"别", bie3:"瘪", bie4:"别",
  biao1:"标", biao3:"表", biao4:"鳔",
  bin1:"宾", bin4:"鬓",
  bing1:"冰", bing3:"丙", bing4:"病",
  bu1:"逋", bu2:"醭", bu3:"补", bu4:"不",
  // p
  pa1:"啪", pa2:"爬", pa4:"怕",
  po1:"坡", po2:"婆", po3:"叵", po4:"破",
  pai1:"拍", pai2:"排", pai3:"迫", pai4:"派",
  pei1:"胚", pei2:"陪", pei4:"配",
  pao1:"抛", pao2:"刨", pao3:"跑", pao4:"炮",
  pou1:"剖", pou2:"裒",
  pan1:"攀", pan2:"盘", pan4:"判",
  pen1:"喷", pen2:"盆", pen4:"喷",
  pang1:"乓", pang2:"旁", pang3:"耪", pang4:"胖",
  peng1:"烹", peng2:"朋", peng3:"捧", peng4:"碰",
  pi1:"批", pi2:"皮", pi3:"匹", pi4:"屁",
  pie1:"撇", pie3:"撇",
  piao1:"飘", piao2:"瓢", piao3:"漂", piao4:"票",
  pin1:"拼", pin2:"贫", pin3:"品", pin4:"聘",
  ping1:"乒", ping2:"平",
  pu1:"扑", pu2:"仆", pu3:"普", pu4:"铺",
  // m
  ma1:"妈", ma2:"麻", ma3:"马", ma4:"骂",
  mo1:"摸", mo2:"摩", mo3:"抹", mo4:"末",
  me5:"么",
  mai2:"埋", mai3:"买", mai4:"卖",
  mei2:"没", mei3:"美", mei4:"妹",
  mao1:"猫", mao2:"毛", mao3:"卯", mao4:"冒",
  mou1:"哞", mou2:"谋", mou3:"某",
  man2:"瞒", man3:"满", man4:"慢",
  men1:"闷", men2:"门", men4:"闷",
  mang2:"忙", mang3:"莽",
  meng1:"蒙", meng2:"盟", meng3:"猛", meng4:"梦",
  mi1:"咪", mi2:"迷", mi3:"米", mi4:"密",
  mie1:"乜", mie4:"灭",
  miao1:"喵", miao2:"苗", miao3:"秒", miao4:"妙",
  miu4:"谬",
  min2:"民", min3:"敏",
  ming2:"明", ming3:"酩", ming4:"命",
  mu2:"模", mu3:"母", mu4:"木",
  // f
  fa1:"发", fa2:"罚", fa3:"法", fa4:"发",
  fo2:"佛",
  fei1:"飞", fei2:"肥", fei3:"匪", fei4:"费",
  fou3:"否",
  fan1:"翻", fan2:"烦", fan3:"反", fan4:"饭",
  fen1:"分", fen2:"坟", fen3:"粉", fen4:"奋",
  fang1:"方", fang2:"房", fang3:"访", fang4:"放",
  feng1:"风", feng2:"逢", feng3:"讽", feng4:"凤",
  fu1:"夫", fu2:"福", fu3:"府", fu4:"父",
  // d
  da1:"搭", da2:"达", da3:"打", da4:"大",
  de2:"得", de5:"的",
  dai1:"呆", dai3:"歹", dai4:"代",
  dei3:"得",
  dao1:"刀", dao2:"叨", dao3:"导", dao4:"到",
  dou1:"都", dou3:"斗", dou4:"豆",
  dan1:"丹", dan3:"胆", dan4:"但",
  den4:"扽",
  dang1:"当", dang3:"挡", dang4:"荡",
  deng1:"灯", deng3:"等", deng4:"凳",
  di1:"低", di2:"敌", di3:"底", di4:"地",
  die1:"爹", die2:"叠",
  diao1:"刁", diao3:"屌", diao4:"掉",
  diu1:"丢",
  dian1:"颠", dian3:"点", dian4:"电",
  ding1:"丁", ding3:"顶", ding4:"定",
  du1:"督", du2:"读", du3:"赌", du4:"度",
  duo1:"多", duo2:"夺", duo3:"躲", duo4:"舵",
  dui1:"堆", dui4:"对",
  duan1:"端", duan3:"短", duan4:"段",
  dun1:"蹲", dun2:"盹", dun3:"盹", dun4:"顿",
  // t
  ta1:"他", ta3:"塔", ta4:"踏",
  te4:"特",
  tai1:"胎", tai2:"台", tai4:"太",
  tao1:"涛", tao2:"逃", tao3:"讨", tao4:"套",
  tou1:"偷", tou2:"头", tou4:"透",
  tan1:"摊", tan2:"谈", tan3:"坦", tan4:"探",
  tang1:"汤", tang2:"糖", tang3:"躺", tang4:"烫",
  teng2:"疼",
  ti1:"踢", ti2:"提", ti3:"体", ti4:"替",
  tie1:"贴", tie3:"铁",
  tiao1:"挑", tiao2:"条", tiao3:"挑", tiao4:"跳",
  tian1:"天", tian2:"田", tian3:"舔",
  ting1:"听", ting2:"停", ting3:"挺",
  tu1:"突", tu2:"图", tu3:"土", tu4:"兔",
  tuo1:"拖", tuo2:"驼", tuo3:"妥", tuo4:"唾",
  tui1:"推", tui2:"颓", tui3:"腿", tui4:"退",
  tuan1:"湍", tuan2:"团",
  tun1:"吞", tun2:"屯", tun3:"氽", tun4:"褪",
  // n
  na2:"拿", na3:"哪", na4:"那",
  ne4:"讷", ne5:"呢",
  nai3:"奶", nai4:"耐",
  nei3:"馁", nei4:"内",
  nao2:"挠", nao3:"脑", nao4:"闹",
  nou4:"耨",
  nan1:"囡", nan2:"南", nan3:"赧", nan4:"难",
  nen4:"嫩",
  nang1:"囔", nang2:"囊", nang3:"馕", nang4:"齉",
  neng2:"能",
  ni1:"妮", ni2:"泥", ni3:"你", ni4:"逆",
  nie1:"捏", nie4:"聂",
  niao3:"鸟", niao4:"尿",
  niu1:"妞", niu2:"牛", niu3:"扭", niu4:"拗",
  nian1:"蔫", nian2:"年", nian3:"碾", nian4:"念",
  nin2:"您",
  niang2:"娘", niang4:"酿",
  ning2:"宁", ning3:"拧", ning4:"泞",
  nu2:"奴", nu3:"努", nu4:"怒",
  nü3:"女", nü4:"恧",
  nüe4:"虐",
  // l
  la1:"拉", la2:"砬", la3:"喇", la4:"辣",
  le4:"乐", le5:"了",
  lai2:"来", lai4:"赖",
  lei1:"勒", lei2:"雷", lei3:"垒", lei4:"泪",
  lao1:"捞", lao2:"劳", lao3:"老", lao4:"涝",
  lou1:"搂", lou2:"楼", lou3:"搂", lou4:"漏",
  lan2:"蓝", lan3:"懒", lan4:"烂",
  lang1:"啷", lang2:"狼", lang3:"朗", lang4:"浪",
  leng2:"棱", leng3:"冷", leng4:"愣",
  li1:"哩", li2:"梨", li3:"里", li4:"力",
  lia3:"俩",
  lie1:"咧", lie3:"咧", lie4:"列",
  liao1:"撩", liao2:"聊", liao3:"了", liao4:"料",
  liu1:"溜", liu2:"流", liu3:"柳", liu4:"六",
  lian2:"连", lian3:"脸", lian4:"练",
  lin2:"林", lin3:"凛", lin4:"赁",
  liang2:"凉", liang3:"两", liang4:"亮",
  ling2:"灵", ling3:"领", ling4:"另",
  lu1:"撸", lu2:"炉", lu3:"鲁", lu4:"路",
  luo1:"啰", luo2:"罗", luo3:"裸", luo4:"落",
  luan2:"峦", luan3:"卵", luan4:"乱",
  lun1:"抡", lun2:"轮", lun3:"埨", lun4:"论",
  lü2:"驴", lü3:"旅", lü4:"绿",
  lüe4:"略",
  // g
  ga1:"嘎", ga2:"噶", ga3:"尕", ga4:"尬",
  ge1:"哥", ge2:"格", ge3:"葛", ge4:"个",
  gai1:"该", gai3:"改", gai4:"盖",
  gei3:"给",
  gao1:"高", gao3:"搞", gao4:"告",
  gou1:"沟", gou3:"狗", gou4:"够",
  gan1:"干", gan3:"感", gan4:"干",
  gen1:"根", gen2:"哏", gen3:"艮", gen4:"亘",
  gang1:"刚", gang3:"港", gang4:"杠",
  geng1:"耕", geng3:"梗", geng4:"更",
  gu1:"姑", gu2:"骨", gu3:"古", gu4:"故",
  gua1:"瓜", gua3:"寡", gua4:"挂",
  guo1:"锅", guo2:"国", guo3:"果", guo4:"过",
  guai1:"乖", guai3:"拐", guai4:"怪",
  gui1:"归", gui3:"鬼", gui4:"贵",
  guan1:"关", guan3:"管", guan4:"惯",
  gun3:"滚", gun4:"棍",
  guang1:"光", guang3:"广", guang4:"逛",
  // k
  ka1:"咔", ka3:"卡",
  ke1:"科", ke2:"咳", ke3:"可", ke4:"课",
  kai1:"开", kai3:"凯", kai4:"忾",
  kao1:"尻", kao3:"考", kao4:"靠",
  kou1:"抠", kou3:"口", kou4:"扣",
  kan1:"刊", kan3:"砍", kan4:"看",
  ken3:"肯", ken4:"裉",
  kang1:"康", kang2:"扛", kang4:"抗",
  keng1:"坑",
  ku1:"哭", ku3:"苦", ku4:"库",
  kua1:"夸", kua3:"垮", kua4:"跨",
  kuo4:"阔",
  kuai3:"蒯", kuai4:"快",
  kui1:"亏", kui2:"葵", kui3:"傀", kui4:"愧",
  kuan1:"宽", kuan3:"款",
  kun1:"昆", kun3:"捆", kun4:"困",
  kuang1:"筐", kuang2:"狂", kuang3:"夼", kuang4:"况",
  // h
  ha1:"哈", ha2:"蛤", ha3:"哈", ha4:"哈",
  he1:"喝", he2:"和", he4:"贺",
  hai1:"嗨", hai2:"还", hai3:"海", hai4:"害",
  hei1:"黑",
  hao1:"蒿", hao2:"豪", hao3:"好", hao4:"号",
  hou1:"齁", hou2:"喉", hou3:"吼", hou4:"后",
  han1:"憨", han2:"含", han3:"喊", han4:"汉",
  hen2:"痕", hen3:"很", hen4:"恨",
  hang1:"夯", hang2:"行", hang4:"沆",
  heng1:"哼", heng2:"横", heng4:"横",
  hu1:"呼", hu2:"湖", hu3:"虎", hu4:"户",
  hua1:"花", hua2:"华", hua4:"话",
  huo1:"豁", huo2:"活", huo3:"火", huo4:"或",
  huai2:"怀", huai4:"坏",
  hui1:"灰", hui2:"回", hui3:"毁", hui4:"会",
  huan1:"欢", huan2:"还", huan3:"缓", huan4:"换",
  hun1:"昏", hun2:"魂", hun4:"混",
  huang1:"慌", huang2:"黄", huang3:"谎", huang4:"晃",
  // j
  ji1:"鸡", ji2:"急", ji3:"几", ji4:"记",
  jia1:"家", jia2:"夹", jia3:"甲", jia4:"价",
  jie1:"接", jie2:"节", jie3:"姐", jie4:"借",
  jiao1:"交", jiao2:"嚼", jiao3:"脚", jiao4:"叫",
  jiu1:"究", jiu3:"九", jiu4:"就",
  jian1:"间", jian3:"减", jian4:"见",
  jin1:"今", jin3:"紧", jin4:"近",
  jiang1:"江", jiang3:"讲", jiang4:"匠",
  jing1:"京", jing3:"井", jing4:"静",
  jiong3:"窘",
  ju1:"居", ju2:"局", ju3:"举", ju4:"句",
  jue1:"撅", jue2:"觉", jue3:"蹶", jue4:"倔",
  juan1:"捐", juan3:"卷", juan4:"圈",
  jun1:"军", jun4:"俊",
  // q
  qi1:"七", qi2:"齐", qi3:"起", qi4:"气",
  qia1:"掐", qia3:"卡", qia4:"恰",
  qie1:"切", qie2:"茄", qie3:"且", qie4:"切",
  qiao1:"敲", qiao2:"桥", qiao3:"巧", qiao4:"俏",
  qiu1:"秋", qiu2:"求",
  qian1:"千", qian2:"前", qian3:"浅", qian4:"欠",
  qin1:"亲", qin2:"勤", qin3:"寝", qin4:"沁",
  qiang1:"枪", qiang2:"墙", qiang3:"抢", qiang4:"呛",
  qing1:"青", qing2:"晴", qing3:"请", qing4:"庆",
  qiong2:"穷",
  qu1:"区", qu2:"渠", qu3:"取", qu4:"去",
  que1:"缺", que2:"瘸", que4:"却",
  quan1:"圈", quan2:"全", quan3:"犬", quan4:"劝",
  qun2:"群",
  // x
  xi1:"西", xi2:"习", xi3:"洗", xi4:"系",
  xia1:"瞎", xia2:"霞", xia4:"下",
  xie1:"些", xie2:"鞋", xie3:"写", xie4:"谢",
  xiao1:"消", xiao2:"淆", xiao3:"小", xiao4:"笑",
  xiu1:"休", xiu3:"朽", xiu4:"秀",
  xian1:"先", xian2:"咸", xian3:"显", xian4:"现",
  xin1:"新", xin2:"寻", xin4:"信",
  xiang1:"香", xiang2:"详", xiang3:"想", xiang4:"向",
  xing1:"星", xing2:"行", xing3:"醒", xing4:"姓",
  xiong1:"兄", xiong2:"熊",
  xu1:"需", xu2:"徐", xu3:"许", xu4:"序",
  xue1:"靴", xue2:"学", xue3:"雪", xue4:"血",
  xuan1:"宣", xuan2:"悬", xuan3:"选", xuan4:"炫",
  xun1:"熏", xun2:"寻", xun4:"训",
  // zh
  zha1:"扎", zha2:"炸", zha3:"眨", zha4:"诈",
  zhe1:"遮", zhe2:"折", zhe3:"者", zhe4:"这",
  zhai1:"摘", zhai2:"宅", zhai3:"窄", zhai4:"债",
  zhei4:"这",
  zhao1:"招", zhao2:"着", zhao3:"找", zhao4:"照",
  zhou1:"周", zhou2:"轴", zhou3:"肘", zhou4:"宙",
  zhan1:"沾", zhan3:"展", zhan4:"站",
  zhen1:"真", zhen3:"枕", zhen4:"阵",
  zhang1:"张", zhang3:"长", zhang4:"丈",
  zheng1:"争", zheng3:"整", zheng4:"正",
  zhi1:"知", zhi2:"直", zhi3:"只", zhi4:"志",
  zhu1:"猪", zhu2:"竹", zhu3:"主", zhu4:"住",
  zhua1:"抓", zhua3:"爪",
  zhuo1:"桌", zhuo2:"啄",
  zhuai1:"拽", zhuai4:"拽",
  zhui1:"追", zhui4:"坠",
  zhuan1:"专", zhuan3:"转", zhuan4:"赚",
  zhun1:"谆", zhun3:"准",
  zhuang1:"装", zhuang4:"壮",
  // ch
  cha1:"插", cha2:"茶", cha3:"衩", cha4:"差",
  che1:"车", che3:"扯", che4:"彻",
  chai1:"拆", chai2:"柴",
  chao1:"超", chao2:"朝", chao3:"炒",
  chou1:"抽", chou2:"愁", chou3:"丑", chou4:"臭",
  chan1:"搀", chan2:"缠", chan3:"产", chan4:"颤",
  chen1:"嗔", chen2:"沉", chen3:"碜", chen4:"趁",
  chang1:"昌", chang2:"长", chang3:"场", chang4:"唱",
  cheng1:"称", cheng2:"成", cheng3:"逞", cheng4:"秤",
  chi1:"吃", chi2:"迟", chi3:"尺", chi4:"翅",
  chu1:"出", chu2:"除", chu3:"楚", chu4:"处",
  chua1:"歘",
  chuo1:"戳", chuo4:"绰",
  chuai1:"揣", chuai3:"揣", chuai4:"踹",
  chui1:"吹", chui2:"垂",
  chuan1:"穿", chuan2:"传", chuan3:"喘", chuan4:"串",
  chun1:"春", chun2:"纯", chun3:"蠢",
  chuang1:"窗", chuang2:"床", chuang3:"闯", chuang4:"创",
  // sh
  sha1:"沙", sha3:"傻", sha4:"啥",
  she1:"奢", she2:"蛇", she3:"舍", she4:"社",
  shai1:"筛", shai3:"色", shai4:"晒",
  shei2:"谁",
  shao1:"烧", shao2:"勺", shao3:"少", shao4:"少",
  shou1:"收", shou2:"熟", shou3:"手", shou4:"受",
  shan1:"山", shan3:"闪", shan4:"善",
  shen1:"深", shen2:"神", shen3:"沈", shen4:"甚",
  shang1:"伤", shang3:"赏", shang4:"上",
  sheng1:"生", sheng2:"绳", sheng3:"省", sheng4:"胜",
  shi1:"师", shi2:"十", shi3:"史", shi4:"是",
  shu1:"书", shu2:"熟", shu3:"数", shu4:"树",
  shua1:"刷", shua3:"耍",
  shuo1:"说", shuo4:"硕",
  shuai1:"摔", shuai3:"甩", shuai4:"帅",
  shui2:"谁", shui3:"水", shui4:"睡",
  shuan1:"拴", shuan4:"涮",
  shun3:"吮", shun4:"顺",
  shuang1:"双", shuang3:"爽",
  // r
  re3:"惹", re4:"热",
  rao2:"饶", rao3:"扰", rao4:"绕",
  rou2:"柔", rou3:"糅", rou4:"肉",
  ran2:"然", ran3:"染",
  ren2:"人", ren3:"忍", ren4:"认",
  rang1:"嚷", rang2:"瓤", rang3:"嚷", rang4:"让",
  reng1:"扔", reng2:"仍",
  ri4:"日",
  ru2:"如", ru3:"乳", ru4:"入",
  ruo4:"弱",
  rui3:"蕊", rui4:"锐",
  ruan2:"堧", ruan3:"软",
  run4:"润",
  // z
  za1:"扎", za2:"杂", za3:"咋",
  ze2:"则", ze4:"仄",
  zai1:"灾", zai3:"宰", zai4:"再",
  zei2:"贼",
  zao1:"遭", zao2:"凿", zao3:"早", zao4:"造",
  zou1:"邹", zou3:"走", zou4:"奏",
  zan1:"簪", zan2:"咱", zan3:"攒", zan4:"赞",
  zen3:"怎", zen4:"谮",
  zang1:"脏", zang3:"驵", zang4:"葬",
  zeng1:"增", zeng4:"赠",
  zi1:"资", zi3:"子", zi4:"字",
  zu1:"租", zu2:"足", zu3:"组",
  zuo1:"作", zuo2:"昨", zuo3:"左", zuo4:"做",
  zui3:"嘴", zui4:"最",
  zuan1:"钻", zuan3:"缵", zuan4:"赚",
  zun1:"尊", zun3:"撙",
  // c
  ca1:"擦", ca3:"礤",
  ce4:"册",
  cai1:"猜", cai2:"才", cai3:"采", cai4:"菜",
  cao1:"操", cao2:"槽", cao3:"草",
  cou4:"凑",
  can1:"参", can2:"残", can3:"惨", can4:"灿",
  cen1:"参", cen2:"岑",
  cang1:"仓", cang2:"藏",
  ceng1:"噌", ceng2:"层", ceng4:"蹭",
  ci1:"疵", ci2:"词", ci3:"此", ci4:"次",
  cu1:"粗", cu2:"殂", cu4:"醋",
  cuo1:"搓", cuo2:"痤", cuo3:"撮", cuo4:"错",
  cui1:"催", cui3:"璀", cui4:"脆",
  cuan1:"蹿", cuan2:"攒", cuan4:"窜",
  cun1:"村", cun2:"存", cun3:"忖", cun4:"寸",
  // s
  sa1:"撒", sa3:"洒", sa4:"萨",
  se4:"色",
  sai1:"塞", sai4:"赛",
  sao1:"骚", sao3:"扫", sao4:"臊",
  sou1:"搜", sou3:"叟", sou4:"嗽",
  san1:"三", san3:"散", san4:"散",
  sen1:"森",
  sang1:"桑", sang3:"嗓", sang4:"丧",
  seng1:"僧",
  si1:"思", si3:"死", si4:"四",
  su1:"苏", su2:"俗", su4:"速",
  suo1:"缩", suo3:"所",
  sui1:"虽", sui2:"随", sui3:"髓", sui4:"岁",
  suan1:"酸", suan4:"算",
  sun1:"孙", sun3:"损",
};

// Chuyển vận mẫu dạng DB (v, ve, van, vn, iu, ui, un) sang pinyin chuẩn
// để ghép khoá tra cứu.
function normalizeFinal(initial: string, final: string): string {
  // j/q/x + ü viết thành u
  if (["j", "q", "x"].includes(initial)) {
    const m: Record<string, string> = { v: "u", ve: "ue", van: "uan", vn: "un" };
    if (m[final]) return m[final];
  }
  const m: Record<string, string> = {
    v: "ü", ve: "üe", van: "üan", vn: "ün",
    iu: "iu", ui: "ui", un: "un",
  };
  return m[final] ?? final;
}

// Trả về chữ Hán đại diện cho (thanh mẫu + vận mẫu + thanh điệu), nếu có.
export function getHanzi(initial: string, final: string, toneNum: number): string | null {
  const f   = normalizeFinal(initial, final);
  const key = `${initial}${f}${toneNum}`;
  return PINYIN_TO_HANZI[key] ?? null;
}
